name: Build
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

env:
  imageName: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go test ./...
      - run: go build

      - name: 'Container: Build and publish dev image'
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker buildx build --tag ${{ env.imageName }} .
          docker push ${{ env.imageName }}

  test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build
    services:
      cache:
        image: ghcr.io/${{ github.repository }}
        env:
          repository: ghcr.io/${{ github.repository }}/bazel-cache
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd test
          ./upload.sh
          ./download.sh
